Add plans stream.
singer-io/tap-invoiced pull request #2
Opened 2023-03-16 16:05 UTC by zbrak

Need additional source of plans endpoint.

Hypothetically given this has an `updated_at` property the existing tap should work after viewing the new schema?

# Description of change
Adding `plans` stream to tap. Have added schema & updated `sync.py` file to include the new stream.

# Manual QA steps
 - Successful run and output from tap-invoiced fork to target-jsonl.
 - performed catalog output and discovery successful.
 
# Risks
 - `updated_at` is an integer rather than a string timestamp, unsure if the existing tap can support it.
 
# Rollback steps
 - revert this branch

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204121209647802

2023-03-17 18:15 UTC, jaredtking requested changes
One small change needed and then I will approve it

2023-03-17 18:15 UTC, jaredtking commented on tap_invoiced/schemas/plans.json
> +        "string"
This type should be an array of objects or null

2023-03-17 19:50 UTC, zbrak commented on tap_invoiced/schemas/plans.json
> +    },
```suggestion
        "object"
      ],
      "properties": {}
    },
```

2023-03-17 20:03 UTC, zbrak commented on tap_invoiced/schemas/plans.json
> +    },
@jaredtking thanks so much for the help here! I've updated `tiers` to match the same as `metadata` property is being handled across other schemas.

2023-03-17 21:22 UTC, jaredtking approved these changes

2023-03-21 14:07 UTC, dmosorast approved these changes
Thanks for the PR @zbrak and thank you for reviewing @jaredtking! Looks straightforward and simple enough to merge. 🚀

2023-03-21 14:07 UTC, merged